### ISSUE TITLE
Ik problem of phantomX

### ISSUE THREAD

**Issue by robotfan4** [KevinOchs/hexapod_ros#17]
Hi, thank you for your great work.
The IK class works well with the 4 DOF legs, however, it can't get the correct joint angles for the phantomX robot. Could you give me some suggestions?

**Comment by r3n33** [comment]
Could you please try to describe the problem that you are having in more detail? I cloned the current source on my PhantomX, compiled and executed:

`roslaunch hexapod_bringup hexapod_simple.launch config:=phantomX joy_mapping:=joystick_ds4`

The IK is solving for 3dof without problems and the robot is able to walk around.

**Comment by KevinOchs** [comment]
R3n33 is correct, make sure you are using the proper config at launch and all should work well. Using the one that is called by default is Golem's and will not work properly on a phantomX.

**Comment by robotfan4** [comment]
thank you for your quick answer, i will use a clear workspace and check it further.

**Comment by robotfan4** [comment]
I don't have a joy stick, so i write a node to use a
[source code and video.tar.gz](https://github.com/KevinOchs/hexapod_ros/files/331142/source.code.and.video.tar.gz)
[source code and video.tar.gz](https://github.com/KevinOchs/hexapod_ros/files/331143/source.code.and.video.tar.gz)
[source code and video.zip](https://github.com/KevinOchs/hexapod_ros/files/331146/source.code.and.video.zip)
[source code and video.zip](https://github.com/KevinOchs/hexapod_ros/files/331148/source.code.and.video.zip)



 keyboard to simulate the joy_stick message, press key "1 " for standing up, "w" for moving  forward. 
I modified the the hexapod_simple.launch and got  the "/cmd_vel" topic like this: 

linear: 
  x: 0.0787199493647
  y: -0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

It should work for the robot, however i got a mess movement for the PhantonX and a nice movement for the Golem, As the video in the attachment. if you have time please check it.
Bests.
Here is the video and the code on google drive:
https://drive.google.com/open?id=0B5ypkGAlu2KURVNvMFZyTmx5LU0

**Comment by KevinOchs** [comment]
Your command velocity looks high for a phantomx. Is the terminal giving you warnings of IK failing??

**Comment by robotfan4** [comment]
nope.

**Comment by KevinOchs** [comment]
Are you using a picture of my Golem project as your profile picture?

**Comment by robotfan4** [comment]
while i am sorry about that, that's some work about the map based hexapod motion planning. I will change it, sorry again for that potential copyright conflicts.

**Comment by KevinOchs** [comment]
No worries... So your video does look odd for the phantomX. Did you change the yaml for at all? If not there might be an error in either the xacro file for the phantomX or the yaml config file.

**Comment by KevinOchs** [comment]
The screen top, outer legs look very wrong. R3n33 does the physical robot walk properly? If physical is walking properly that means the joint state is correct since the servos are controlled by that.  If it is just wrong in rviz this might be an easy fix. robotfan can you compare my Golem xacro file to the phantomX xacro file? Ignoring the tarsus of course.

**Comment by KevinOchs** [comment]
R3n33 messaged me the robot physical is fine. So we must have a bug in the robot xacro file.

(BTW your robot in your avatar look fantastic!)

**Comment by robotfan4** [comment]
Thank you for your commends, I control my robot based on the ros crab hexapod robot project. 

I compare the two xacros, Does the phantomX xacro need a foot link?

**Comment by KevinOchs** [comment]
It appears the coxa axis is backwards. Line 194 <axis xyz="0.0 0.0 ${-axis}" /> should be <axis xyz="0.0 0.0 1.0/> 


Try that.

**Comment by KevinOchs** [comment]
And yes the phantomX could use a foot joint. Especially if you are going to use Gazebo

**Comment by robotfan4** [comment]
yes, that works! thank you a lot!

**Comment by KevinOchs** [comment]
Issue is now fixed and updated in both master and indigo branch
