### ISSUE TITLE
The initialization of pose_th_,pose_x_ and pose_y_

### ISSUE THREAD

**Issue by robotfan4** [KevinOchs/hexapod_ros#19]
You should initialize pose_th_,pose_x_ and pose_y_ equal to zero at the construct function of control.cpp  When i using the fake odom tf, it works perfectly on one machine, but becomes weird on the other machine. I finally found that some machine give a random initial value instead zero...
Bests.

**Comment by romainreignier** [comment]
Nice catch, you should submit a pull request.

**Comment by KevinOchs** [comment]
This has been addressed!
