### ISSUE TITLE
Wrong ID in phantomX.yaml

### ISSUE THREAD

**Issue by ChrisHexapod** [KevinOchs/hexapod_ros#25]
Hi,

I'm just testing the stack on a RPI4 and a PhantomX MarkIII. It seems that the phamtonX.yaml file has a small problem regarding servo ID's.

In detail     

    16': {name: coxa_joint_LF, type: AX, id: 19, ticks: 1024, center: 512, max_radians: !degrees 300, sign: 1, offset: !degrees 0},

should be

    '16': {name: coxa_joint_LF, type: AX, id: 1, ticks: 1024, center: 512, max_radians: !degrees 300, sign: 1, offset: !degrees 0},

and lines 
    '19': {name: pan_joint, type: AX, id: 20, ticks: 1024, center: 512, max_radians: !degrees 300, sign: 1, offset: !degrees 0},
    '20': {name: tilt_joint, type: AX, id: 21, ticks: 1024, center: 512, max_radians: !degrees 300, sign: 1, offset: !degrees 0}

should become

    '19': {name: pan_joint, type: AX, id: 19, ticks: 1024, center: 512, max_radians: !degrees 300, sign: 1, offset: !degrees 0},
    '20': {name: tilt_joint, type: AX, id: 20, ticks: 1024, center: 512, max_radians: !degrees 300, sign: 1, offset: !degrees 0}

Cheers,

 Christ

**Comment by KevinOchs** [comment]
I've never owned a PhantomX MarkIII so whoever submitted that configuration might have had them switched. I think I added that file just as an example to show the ability to configure as you need. 

Cheers,
Kevin
